/* Generated By:JavaCC: Do not edit this line. CalculadoraConstants.java */
package manejoerrores;
/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculadoraConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 4;
  /** RegularExpression Id. */
  int MAS = 5;
  /** RegularExpression Id. */
  int MENOS = 6;
  /** RegularExpression Id. */
  int POR = 7;
  /** RegularExpression Id. */
  int ENTRE = 8;
  /** RegularExpression Id. */
  int IGUAL = 9;
  /** RegularExpression Id. */
  int CONSTANTE = 10;
  /** RegularExpression Id. */
  int DIGITO = 11;
  /** RegularExpression Id. */
  int VARIABLE = 12;
  /** RegularExpression Id. */
  int LETRA = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "<CONSTANTE>",
    "<DIGITO>",
    "<VARIABLE>",
    "<LETRA>",
    "\"(\"",
    "\")\"",
  };

}
